[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1

# [target.wasm32-unknown-unknown]
# runner = "wasm-server-runner"
